#!/bin/bash

# Script to launch temp monitoiring and store output in two log files saved in different locations.
# The script goes to crontab as > */30 * * * * script 

# Set global vars
TODAY=$(date +%Y%m%d)
TIME=$(date +%T)

# Create log files
NAS_FILE=/path/to/NAS/"temp-check.$1.$TODAY.$TIME"
LOCAL_FILE=/path/to/local/"temp-check.$1.$TODAY.$TIME"

touch $NAS_FILE
touch $LOCAL_FILE

# Script
echo $1 | tee -a $NAS_FILE $LOCAL_FILE
echo $TIME | tee -a $NAS_FILE $LOCAL_FILE
sensors | tee -a $NAS_FILE $LOCAL_FILE
sudo hddtemp /dev/sda | tee -a $NAS_FILE $LOCAL_FILE
echo "#" | tee -a $NAS_FILE $LOCAL_FILE
